### ISSUE TITLE
is made with relay modern?

### ISSUE THREAD

**Issue by webmobiles** [lucasbento/graphql-pokemon#6]

**Comment by sibelius** [comment]
no, relay classic

would u mind send a pr to convert it to modern?

**Comment by webmobiles** [comment]
how to do it ? very sad have no examples with relay modern

**Comment by sibelius** [comment]
try this one https://github.com/sibelius/ReactNavigationRelayModern

**Comment by webmobiles** [comment]
thanks, but it's about react native for mobile development ? can use that for an desktop app ? why there is no official starter in relay ? relay modern is not for production yet?. A lot of people develop in apollo , why they choosed instead relay ?

**Comment by lucasbento** [comment]
I'll open an issue later on to consider migrating to Relay Modern or Apollo but right now is not the moment for that, thanks for opening this though.
