### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by jaydenseric** [lucasbento/graphql-pokemon#9]
The server seems to be down, which unfortunately makes all the demos I maintain that use it unusable:

- https://graphql-react.now.sh
- https://github.com/zeit/next.js/tree/canary/examples/with-graphql-react

**Comment by lucasbento** [comment]
@jaydenseric: thanks for opening this issue, apologies for the delay on replying as I was in Berlin a few days ago and yesterday I was swamped in work.

It should be working fine now, I think there was a problem on `now` itself as I just deployed it again and it works, can you please confirm?

**Comment by jaydenseric** [comment]
Much better, thanks 🙌
